[package]
name = "eff-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.29", features = ["derive"]}
image = "0.24.5"
anyhow = "1.0.66"

[dependencies.eff]
path = "../lib"